import "./globals.css";
import Header from "@/components/section/Header";
import Footer from "@/components/section/Footer";
import { Inter } from "next/font/google";
import StoreProvider from "../providers/StoreProvider";
import AuthProvider from "@/providers/AuthProvider";
import { Toaster } from "@/components/ui/sonner"
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "StreamHub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${inter.className} antialiased`}
      >
        <StoreProvider>
          <AuthProvider>
            <Header />
            {children}
            <Footer />
            <Toaster />
          </AuthProvider>
        </StoreProvider>
      </body>
    </html>
  );
}